// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWfT4pZfv15PRSZxMxAsvv2GRaUfOVFGs',
    appId: '1:165946365384:web:4a9ce65e4d77a39fec9cfd',
    messagingSenderId: '165946365384',
    projectId: 'bookietest-75f8c',
    authDomain: 'bookietest-75f8c.firebaseapp.com',
    storageBucket: 'bookietest-75f8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypEx8vEzH8w_0iTMydlp0zR2hvcrXb8I',
    appId: '1:165946365384:android:476cda323ac4820eec9cfd',
    messagingSenderId: '165946365384',
    projectId: 'bookietest-75f8c',
    storageBucket: 'bookietest-75f8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsT26J3aspjdGmxISpdziLDNF2MwEvpA',
    appId: '1:165946365384:ios:4c67b291f53c56f8ec9cfd',
    messagingSenderId: '165946365384',
    projectId: 'bookietest-75f8c',
    storageBucket: 'bookietest-75f8c.firebasestorage.app',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsT26J3aspjdGmxISpdziLDNF2MwEvpA',
    appId: '1:165946365384:ios:4c67b291f53c56f8ec9cfd',
    messagingSenderId: '165946365384',
    projectId: 'bookietest-75f8c',
    storageBucket: 'bookietest-75f8c.firebasestorage.app',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWfT4pZfv15PRSZxMxAsvv2GRaUfOVFGs',
    appId: '1:165946365384:web:1d84b863fade2c98ec9cfd',
    messagingSenderId: '165946365384',
    projectId: 'bookietest-75f8c',
    authDomain: 'bookietest-75f8c.firebaseapp.com',
    storageBucket: 'bookietest-75f8c.firebasestorage.app',
  );
}
