// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Y_l1TKMl6O6uu1B1lXgpM9pO_KFc_t4',
    appId: '1:678793709152:web:87aa8a1251cecc4d42a505',
    messagingSenderId: '678793709152',
    projectId: 'h3-14-bookie',
    authDomain: 'h3-14-bookie.firebaseapp.com',
    storageBucket: 'h3-14-bookie.firebasestorage.app',
    measurementId: 'G-55FEF80LQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjB8ag8sJKIDEFEi2P6kfFTwEly2yETao',
    appId: '1:678793709152:android:52afdfcad3a4199c42a505',
    messagingSenderId: '678793709152',
    projectId: 'h3-14-bookie',
    storageBucket: 'h3-14-bookie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRX0vyMJjSksU9egg_s9qDHHi2wxDV83k',
    appId: '1:678793709152:ios:d59743ee477866f442a505',
    messagingSenderId: '678793709152',
    projectId: 'h3-14-bookie',
    storageBucket: 'h3-14-bookie.firebasestorage.app',
    androidClientId: '678793709152-tl33qp6nn7uje48nep8gloqo6s87rj2n.apps.googleusercontent.com',
    iosClientId: '678793709152-ru98epv8o2jfq03nt2pa5n55o0uvgrdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRX0vyMJjSksU9egg_s9qDHHi2wxDV83k',
    appId: '1:678793709152:ios:d59743ee477866f442a505',
    messagingSenderId: '678793709152',
    projectId: 'h3-14-bookie',
    storageBucket: 'h3-14-bookie.firebasestorage.app',
    androidClientId: '678793709152-tl33qp6nn7uje48nep8gloqo6s87rj2n.apps.googleusercontent.com',
    iosClientId: '678793709152-ru98epv8o2jfq03nt2pa5n55o0uvgrdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Y_l1TKMl6O6uu1B1lXgpM9pO_KFc_t4',
    appId: '1:678793709152:web:87aa8a1251cecc4d42a505',
    messagingSenderId: '678793709152',
    projectId: 'h3-14-bookie',
    authDomain: 'h3-14-bookie.firebaseapp.com',
    storageBucket: 'h3-14-bookie.firebasestorage.app',
    measurementId: 'G-55FEF80LQK',
  );

}